/**
 * Known creditor names, sourced from the Coastal Debt "Creditors List - Main"
 * sheet (creditor column only). Used as the typeahead source when adding a
 * debt. Users may still enter a creditor not on this list.
 *
 * 309 entries. To refresh, re-run scripts/gen-creditors.mjs.
 */
export const KNOWN_CREDITORS: string[] = [
  "AmerFi",
  "BHG",
  "Bluevine",
  "Can Capital",
  "CBSG",
  "Clover",
  "Elevate",
  "Elevation Capital Group",
  "Family Business Fund",
  "Funding Circle",
  "GreenBox",
  "GRP Funding",
  "Headway Capital",
  "Jolt",
  "Kabbage",
  "Lendr",
  "LoanMe",
  "Merchant Capital Group",
  "Paypal",
  "QS Capital Partners",
  "Quickbooks",
  "Quickbridge",
  "Quicksilver Capital",
  "Rapid Advance",
  "Small Business Funding Solutions",
  "Swift",
  "Web Bank",
  "White Road",
  "Olympus",
  "On Deck",
  "Ondeck",
  "Arsenal",
  "FundBox",
  "Good Funding",
  "Kapitus",
  "Bitty",
  "Allegancy Resources",
  "Alva Advance",
  "Aquina Praxis Line",
  "Ascentium Capital",
  "CashFund",
  "Caymus",
  "Channel Partners",
  "Coconut Funding",
  "Core Financial",
  "Crestmont Capital",
  "EBF",
  "eFinancial Tree",
  "Emerald group holdings",
  "Empire Recovery",
  "Everest",
  "Flexibility Capital",
  "Forever Funding",
  "Fortress Merchant Solutions",
  "Forward Financing",
  "Ironwood Finance",
  "Iruka",
  "Jet Funding",
  "McKenzie",
  "Milestone",
  "MNS Funding",
  "National Funding",
  "Orange Funding",
  "Pierce Capital",
  "QFS",
  "Reliant",
  "Skyinance",
  "Sound Advance",
  "SPG",
  "Splash",
  "Star Advance",
  "SUMMIT FUNDING DOES EQUIPTMENT LOANS (MAKE SURE ITS MCA)",
  "Suncoast",
  "Surfside Capital",
  "Vader",
  "Velocity",
  "VitalCap Fund",
  "Wells Advance",
  "World Global Funding",
  "Xpress Capital",
  "Quick Funding Group",
  "Webfunder",
  "24 Capital",
  "Ace Funding",
  "Advance Service Group",
  "Advance Servicing Inc",
  "Advantage Capital Funding",
  "AJ Equity",
  "Alternative Funding",
  "Amsterdam Capital Solutions",
  "Arcarius Funding",
  "Arena Funding",
  "Arsenal Funding",
  "Avanza Capital",
  "BCA",
  "Beckham Capital",
  "BizFund LLC",
  "Blade Funding",
  "Blue Sky Advance",
  "Bow Apple Capital",
  "Brickstone",
  "Bridge Funding Cap",
  "Broadway",
  "Business Backer",
  "ByzFunder",
  "Camino Financial Inc",
  "Canacap",
  "Capital Assist",
  "Capitalize Group LLC",
  "Capybara",
  "Capytal.com",
  "Cash Capital",
  "Cashable",
  "Cashfloit",
  "CFG",
  "Churchhill",
  "Clearfund Solutions, LLC",
  "Cloudfund",
  "Core Funding",
  "Comprehensive",
  "Credibly of AZ",
  "Cromwell Capital",
  "Delta Bridge Funding",
  "Diesel funding",
  "Direct Merchant Fudning",
  "Diverse Capital",
  "Dynasty Capital",
  "E Advance Services",
  "Eagle Eye",
  "East Shore Equities, LLC",
  "Edge Capital",
  "Emmy Capital",
  "Epic Advance",
  "Essential",
  "Expansion Capital",
  "Fenix Capital (CHANGE BANKS !)",
  "Fidelity Funding",
  "Fintap",
  "Flash Advance",
  "Fora Financial",
  "Fox Capital Group",
  "Fox Funding",
  "Fox Business Funding",
  "Fratello",
  "Fundamental Capital",
  "FundFi",
  "FundPro",
  "Funding Metrics",
  "FundKite",
  "FundWorks - Trace Beers",
  "Fusion Funding",
  "GCM Capital",
  "Gemini",
  "GFE",
  "Globex Funding",
  "Global Merchant Cash",
  "GMC Funding",
  "Green Note Capital",
  "Greenwich Capital",
  "HFH",
  "Highland Hill",
  "Hybrid",
  "Idea 247",
  "Ideal Funding",
  "iFund Co",
  "In Advance",
  "IOU Financial",
  "IRM Ventures",
  "Itria Ventures",
  "Kalamata Capital Group, LLC",
  "Knightsbridge Capital",
  "Launch",
  "LCF / Last Chance Funding",
  "Legend",
  "Lendini",
  "LG Funding",
  "Libertas",
  "Mantis",
  "Mint Funding",
  "MCA Servicing",
  "MCA World",
  "Mega",
  "Merchant Cash Source",
  "Merk Funding",
  "Monday Funding",
  "Mr Advance",
  "Mulligan",
  "Mynt Funding",
  "NewCo Capital",
  "Nexi",
  "Ocean Advance",
  "Ocean Funding",
  "Overton Funding",
  "Pac Western",
  "Parkview",
  "Parkside",
  "Pearl Capital",
  "Phoenix Capital",
  "Pinnacle Lending",
  "Pirs Capital",
  "Premier Capital Funding",
  "Prince Funding",
  "Prosperum Capital",
  "Purple Tree Funding",
  "Queen Funding",
  "Quick Fix",
  "Raptor",
  "RBR Global",
  "RDM Capital Funding",
  "Reliance Funding",
  "River Advance",
  "Roc Funding",
  "Rocket capital",
  "Samson",
  "Seamless Capital",
  "Silverline",
  "Simply Funding",
  "Smart Business Funding",
  "Smart Funding Capital",
  "Smart Step Funding",
  "Sofia Grey LLC",
  "SOS Capital",
  "Spark Funding",
  "Spartan",
  "Specialty Capital",
  "Speedy Advance",
  "Swift Funding Source",
  "The Smarter Merchant",
  "Torro",
  "TVT Capital",
  "Unique Funding Solutions",
  "United First",
  "United Funding",
  "Uptown Funding",
  "Vault Cap, LLC",
  "Vivian Capital",
  "Vox Funding",
  "Wall Funding",
  "Web Funder",
  "Wellen Capital",
  "Westwood",
  "Wide Merchant Group",
  "Yes Capital Group",
  "Zahav",
  "Zinch",
  "KRS Partners",
  "LexicoCapital",
  "Zlur Funding LLC",
  "BOOSTRA FLORIDA CORP",
  "VIBRANT FUNDING LLC",
  "SLATE ADVANCE",
  "Newport Business Capital",
  "Aspire Funding",
  "Wall Street Funding",
  "Star Capital Solutions",
  "Barclays Advance",
  "Lazarus Capital",
  "BIG Blackbridge Investment Group",
  "Cambridge",
  "Grid",
  "Sinclair",
  "Speedy Funding",
  "IMS FUND LLC",
  "GreenTree",
  "Woodmere Fincancial",
  "Link Advance",
  "Novus",
  "FinPoint",
  "Balboa",
  "Banana Exchange",
  "Britecap",
  "Camino Financial",
  "Capital Dude",
  "EIN Capital",
  "Fundio",
  "Fundr",
  "GCap Holdings LLC",
  "Insta",
  "KYF Global",
  "LAG Holdings",
  "Millstone",
  "Novo",
  "Provider Web Capital/ PW Funding",
  "Paladin Funding Group",
  "Rapid",
  "Symplifi",
  "Synergy",
  "Triton Recovery Group",
  "SuperFast Cap",
  "Accord Business Funding",
  "Fast Capital",
  "Invictus Partners LLC",
  "CALI FLOWER CAPITAL",
  "Quantum Lending Solutions",
  "CorePro",
  "Arin Funding",
  "SunBiz Funding",
  "JRG",
  "LionHeart Funding",
  "Giggle",
  "Future Funding",
  "Funding Future",
  "Retro Advance",
  "Comon Cents",
  "Loanability",
  "Cornichello Capital",
  "New York Tribeca Group",
  "Union Funding Source",
  "Funders App",
];
