// Reads generated SVGs in scripts/icons/out/glyphs/ and emits a single
// TS data module: src/components/icons/glyphs-data.ts with the INNER markup of
// each icon (the <svg> wrapper is added by the React component at render time).
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const SRC = resolve(ROOT, "scripts/icons/out/glyphs");
const OUT = resolve(ROOT, "src/components/icons/glyphs-data.ts");

function innerOf(svg) {
  const open = svg.indexOf(">", svg.indexOf("<svg"));
  const close = svg.lastIndexOf("</svg>");
  return svg
    .slice(open + 1, close)
    .replace(/\s+/g, " ")
    .replace(/stroke-width="[^"]*"/g, "") // unify weight via the wrapper
    .replace(/fill="(?!none)[^"]*"/g, "") // drop hardcoded fills, keep fill="none"
    .trim();
}

const files = readdirSync(SRC).filter((f) => f.endsWith(".svg")).sort();
const entries = files.map((f) => {
  const name = f.replace(".svg", "");
  const inner = innerOf(readFileSync(resolve(SRC, f), "utf8")).replace(/`/g, "\\`");
  return `  ${JSON.stringify(name)}: \`${inner}\`,`;
});

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  `// AUTO-GENERATED by scripts/icons/build-glyphs.mjs. Do not edit by hand.\n` +
    `// Inner SVG markup for each playful glyph; viewBox is 0 0 24 24.\n` +
    `export const GLYPH_PATHS: Record<string, string> = {\n${entries.join("\n")}\n};\n\n` +
    `export type GlyphName = keyof typeof GLYPH_PATHS;\n`
);
console.log(`wrote ${files.length} glyphs -> src/components/icons/glyphs-data.ts`);

// Drop-in module that mirrors the lucide-react named exports we use, so
// `import { Search } from "@/components/icons/lucide"` works unchanged.
const LUCIDE = resolve(ROOT, "src/components/icons/lucide.tsx");
const names = files.map((f) => f.replace(".svg", ""));
const exports = names.map((n) => `export const ${n} = makeGlyph(${JSON.stringify(n)});`).join("\n");
writeFileSync(
  LUCIDE,
  `// AUTO-GENERATED by scripts/icons/build-glyphs.mjs. Do not edit by hand.\n` +
    `// Drop-in replacement for lucide-react: same component names, custom playful glyphs.\n` +
    `import { makeGlyph } from "./Icon";\n\n${exports}\n`
);
console.log(`wrote ${names.length} named exports -> src/components/icons/lucide.tsx`);
