// Icon manifest + shared style. One source of truth for the whole set.

// Locked style brief, appended to every hero-icon prompt. The _anchor.png
// reference is also passed on every call to hold the look steady.
export const STYLE = `Playful hand-illustrated app icon in a flat modern style. Rounded, friendly, slightly chunky line-and-fill shapes. Lead accent color #3052FF (Coastal blue) with soft lighter-blue tints and clean white highlights; very small touches of warm accent allowed. Subtle soft drop shadow beneath the object. Centered, even padding, single clear subject, square composition. FULLY TRANSPARENT background (alpha), no background panel, no border, no frame, no text, no letters, no words. Match the visual style, line weight, color palette and shading of the reference image exactly.`;

// 24 object / entity tile icons. key = ENTITY_ICONS key in object-icons.ts.
export const TILES = [
  ["Dashboard",   "a dashboard with charts and a gauge (home base)"],
  ["Lead",        "a glowing person silhouette with a small spark/star (a new sales lead)"],
  ["Account",     "a modern office building (a business account)"],
  ["Contact",     "a friendly person ID/contact card with a small avatar"],
  ["Opportunity", "two hands shaking over a small coin (a sales opportunity / deal)"],
  ["Client",      "a happy family/household under a small roof (an enrolled client)"],
  ["Creditor",    "a bank building with a small dollar sign (a creditor)"],
  ["Case",        "a support briefcase/folder with a small headset (a service case)"],
  ["ProgramPlan", "a clipboard with a checklist and a small calendar (a program plan)"],
  ["Draft",       "a bank check / invoice with a small pencil (a scheduled draft payment)"],
  ["Offer",       "a price tag with a percent symbol (a settlement offer)"],
  ["Settlement",  "a handshake sealing a document with a checkmark (a finalized settlement)"],
  ["Fee",         "a stack of coins with a small receipt (a fee)"],
  ["Task",        "a checklist with one item checked off (a task)"],
  ["Event",       "a calendar page with a small clock (a scheduled event)"],
  ["Email",       "a friendly envelope with a small paper-plane (email)"],
  ["Sms",         "a rounded speech bubble with three dots (SMS / text)"],
  ["Campaign",    "a megaphone with small sparkles (a marketing campaign)"],
  ["User",        "a single friendly person bust portrait (a user)"],
  ["Report",      "a bar chart on a document with a magnifier (a report)"],
  ["Calculator",  "a friendly calculator (a financial calculator)"],
  ["Settings",    "a single rounded gear/cog (settings)"],
  ["Dialer",      "a phone handset with small outgoing call waves (the power dialer)"],
  ["Marketing",   "a funnel with leads dropping in and a small magnet (marketing / lead sources)"],
];

// 9 app-bundle tiles for the App Launcher. key used for the output filename.
export const APPS = [
  ["sales-operations", "a pipeline funnel beside a small dashboard chart (sales operations app)"],
  ["sales-console",    "a headset with a deal/handshake badge (a sales closer console app)"],
  ["customer-service", "a support headset with a heart/chat bubble (customer service app)"],
  ["debt-negotiation", "a balance scale with coins on it (debt negotiation app)"],
  ["backoffice",       "stacked folders with a small gear (back office operations app)"],
  ["marketing-app",    "a megaphone with a funnel (marketing app)"],
  ["sign-docs",        "a document with a signature line and a pen (e-signature app)"],
  ["dialer-app",       "a phone handset with a keypad (power dialer app)"],
  ["admin",            "a shield with a small gear (admin / integrations app)"],
];

// 61 lucide glyphs in use → playful SVG. name = lucide component name (kept so
// the <Icon> wrapper can map 1:1). desc steers the drawing.
export const GLYPHS = [
  ["Activity", "a heartbeat / activity pulse line"],
  ["AlertTriangle", "a warning triangle with an exclamation"],
  ["ArrowDownToLine", "a download arrow pointing down to a line"],
  ["ArrowLeft", "a left arrow"],
  ["ArrowRight", "a right arrow"],
  ["ArrowUpFromLine", "an upload arrow pointing up from a line"],
  ["Bell", "a notification bell"],
  ["Calendar", "a calendar page"],
  ["CalendarClock", "a calendar with a small clock"],
  ["Check", "a single checkmark"],
  ["Clock", "a clock face with two hands"],
  ["Layers", "three stacked layers / sheets"],
  ["CheckCircle", "a checkmark inside a circle"],
  ["CheckCircle2", "a checkmark inside a filled circle"],
  ["CheckIcon", "a single checkmark"],
  ["ChevronDown", "a downward chevron"],
  ["ChevronDownIcon", "a downward chevron"],
  ["ChevronLeft", "a left chevron"],
  ["ChevronRight", "a right chevron"],
  ["ChevronRightIcon", "a right chevron"],
  ["ChevronUpIcon", "an upward chevron"],
  ["CircleIcon", "a simple circle outline"],
  ["Copy", "two overlapping rectangles (copy)"],
  ["DollarSign", "a dollar sign"],
  ["Download", "a download tray arrow"],
  ["Eye", "an open eye"],
  ["EyeOff", "an eye with a slash (hidden)"],
  ["FileText", "a document with text lines"],
  ["Kanban", "three vertical kanban columns"],
  ["Landmark", "a classical bank building with columns"],
  ["LayoutGrid", "a 2x2 grid"],
  ["LayoutList", "a list layout with rows"],
  ["Loader2", "a circular loading spinner arc"],
  ["LogOut", "a door with an exit arrow"],
  ["Mail", "an envelope"],
  ["Menu", "three stacked horizontal lines (hamburger menu)"],
  ["MessageSquare", "a square speech bubble"],
  ["MoreHorizontal", "three horizontal dots"],
  ["Pause", "two vertical pause bars"],
  ["Pencil", "a pencil (edit)"],
  ["Phone", "a phone handset"],
  ["PhoneIncoming", "a phone handset with an incoming arrow"],
  ["PhoneOutgoing", "a phone handset with an outgoing arrow"],
  ["Play", "a play triangle"],
  ["Plus", "a plus sign"],
  ["RefreshCw", "two circular refresh arrows"],
  ["Save", "a floppy disk (save)"],
  ["Search", "a magnifying glass"],
  ["SearchIcon", "a magnifying glass"],
  ["Send", "a paper plane (send)"],
  ["SkipForward", "a skip-forward double triangle with bar"],
  ["SlidersHorizontal", "horizontal slider controls (filters)"],
  ["Sparkles", "a few sparkle stars"],
  ["Square", "a rounded square outline"],
  ["TableProperties", "a table with a side panel"],
  ["Target", "a concentric target / bullseye"],
  ["TestTube2", "a science test tube"],
  ["Trash2", "a trash can"],
  ["Upload", "an upload tray arrow"],
  ["UserMinus", "a person with a minus (remove user)"],
  ["Users", "two people (a group)"],
  ["XIcon", "an X / close mark"],
  ["Zap", "a lightning bolt"],
  ["ArrowDownLeft", "an arrow pointing down and to the left"],
  ["ArrowUpRight", "an arrow pointing up and to the right"],
  ["BarChart3", "a bar chart with three vertical bars"],
  ["Briefcase", "a briefcase"],
  ["Building2", "a modern multi-story office building"],
  ["ChevronLeftIcon", "a left chevron"],
  ["CircleCheckIcon", "a checkmark inside a circle"],
  ["InfoIcon", "a lowercase letter i inside a circle (info)"],
  ["LayoutDashboard", "a dashboard layout of rectangular panels"],
  ["Lightbulb", "a glowing lightbulb (an idea)"],
  ["Link2", "two interlocking chain links"],
  ["Loader2Icon", "a circular loading spinner arc"],
  ["MapPin", "a map location pin"],
  ["Megaphone", "a megaphone / bullhorn"],
  ["Mic", "a microphone"],
  ["MicOff", "a microphone with a slash through it (muted)"],
  ["OctagonXIcon", "an octagon stop sign with an X inside"],
  ["PhoneCall", "a phone handset with small call waves"],
  ["PhoneOff", "a phone handset with a slash through it"],
  ["ShieldAlert", "a shield with an exclamation mark"],
  ["Tag", "a price tag"],
  ["TrendingDown", "a line trending downward with an arrow"],
  ["TrendingUp", "a line trending upward with an arrow"],
  ["TriangleAlertIcon", "a warning triangle with an exclamation"],
  ["Trophy", "a trophy cup (winner)"],
  ["User", "a single friendly person bust"],
  ["UserCheck", "a person with a small checkmark"],
  ["UserSquare2", "a person inside a rounded square frame"],
  ["X", "an X / close mark"],
  ["Calculator", "a calculator with buttons"],
  ["Settings", "a single gear / cog"],
];

// Avatar set — playful illustrated portraits, diverse, circular-friendly.
export const AVATARS = [
  "a friendly smiling woman with short curly dark hair",
  "a friendly smiling man with a short beard and glasses",
  "a cheerful young woman with long straight black hair",
  "a friendly bald man with warm skin tone",
  "a smiling woman with a headscarf",
  "a friendly man with blond hair and a wide smile",
  "a cheerful woman with shoulder-length red hair",
  "a friendly older man with grey hair and glasses",
  "a smiling woman with an afro hairstyle",
  "a friendly man with dark skin and short hair",
  "a cheerful woman with a ponytail and earrings",
  "a friendly person with glasses and a casual hoodie",
];
