public inherited sharing class CampaignMemberUtil {
    public static final String CAMP_MEMBER_STATUS_PENDING = 'Pending';
    public static final String CAMP_MEMBER_STATUS_FAILED = 'Failed';
    public static final String CAMP_MEMBER_STATUS_COMPLETED = 'Completed';
    public static final String CAMP_MEMBER_STATUS_EMPTY = null;
    public static final String CAMP_MEMBER_FIVE9_ADDED_STATUS = 'Added';
    public static final String CAMP_MEMBER_FIVE9_REMOVED_STATUS = 'Removed';

    public static final Set<String> APPEND_LEAD_STATUS_OPEN = new Set<String> {'Pending', 'Failed', null};
}