'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Modal,ModalButton } from '@/components/slds/modal';
import { toast } from 'sonner';
type Member={id:string;role:string;source:string;user:{name:string;email:string}};
export function AccountTeamManager({accountId}:{accountId:string}){
 const router=useRouter();const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);const[members,setMembers]=useState<Member[]>([]);const[canManage,setCanManage]=useState(false);const[users,setUsers]=useState<{id:string;name:string}[]>([]);const[userId,setUserId]=useState('');const[role,setRole]=useState('Team Member');
 async function load(){setBusy(true);try{const res=await fetch(`/api/accounts/${accountId}/team`);const data=await res.json();if(!res.ok)throw Error(data.error);setMembers(data.members);setCanManage(data.canManage);if(data.canManage){const u=await fetch('/api/users?limit=200');if(u.ok)setUsers((await u.json()).users??[]);}setOpen(true);}catch(e){toast.error(e instanceof Error?e.message:'Could not load team');}finally{setBusy(false);}}
 async function save(memberId?:string){setBusy(true);try{const res=await fetch(`/api/accounts/${accountId}/team`,{method:memberId?'DELETE':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(memberId?{memberId}:{userId,role})});const data=await res.json();if(!res.ok)throw Error(data.error);toast.success('Account team updated');setUserId('');await load();router.refresh();}catch(e){toast.error(e instanceof Error?e.message:'Could not update team');}finally{setBusy(false);}}
 return <><button disabled={busy} className="my-2 rounded border bg-white px-3 py-1 text-sm text-blue-600" onClick={load}>Manage Account Team</button>{open&&<Modal open title="Account Team" onClose={()=>setOpen(false)} footer={<ModalButton onClick={()=>setOpen(false)}>Done</ModalButton>}><p className="mb-3 text-sm">Team members can access this account within their profile permissions.</p>{members.map(m=><div key={m.id} className="flex items-center justify-between border-b py-2 text-sm"><span>{m.user.name} · {m.role}</span>{canManage&&m.source==='MANUAL'&&<button disabled={busy} className="text-red-700" onClick={()=>save(m.id)}>Remove</button>}</div>)}{!members.length&&<p>No explicit team members.</p>}{canManage&&<div className="mt-4 space-y-3"><label className="block">User<select className="ml-2 rounded border p-2" value={userId} onChange={e=>setUserId(e.target.value)}><option value="">Select user</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label className="block">Role<select className="ml-2 rounded border p-2" value={role} onChange={e=>setRole(e.target.value)}>{['Team Member','Closer','Customer Service Rep'].map(r=><option key={r}>{r}</option>)}</select></label><ModalButton variant="brand" disabled={busy||!userId} onClick={()=>save()}>Add Member</ModalButton></div>}</Modal>}</>;
}
