'use client';
import { useState } from 'react';
import Link from 'next/link';
import { parseLeadCsv } from '@/lib/lead-csv';
export default function LeadImport(){
 const [rows,setRows]=useState<Record<string,string>[]>([]);const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[result,setResult]=useState('');
 async function submit(){setBusy(true);setError('');try{const res=await fetch('/api/leads/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rows})});const data=await res.json();if(!res.ok)throw Error(data.error||'Import failed');setResult(`${data.created} leads imported. ${data.skipped} duplicates skipped.`);setRows([]);}catch(e){setError(e instanceof Error?e.message:'Import failed');}finally{setBusy(false);}}
 return <main className="m-6 rounded border bg-white p-6"><Link href="/leads" className="text-blue-600">← Leads</Link><h1 className="my-4 text-2xl font-semibold">Import Leads</h1><p className="mb-4">Upload a CSV with Name, Company, and Phone. Optional columns: Email and Source. Up to 200 rows per import. New leads will be assigned to you. Matching phone and company pairs are skipped.</p><input aria-label="Lead CSV file" type="file" accept=".csv,text/csv" disabled={busy} onChange={async e=>{setError('');setResult('');setRows([]);const file=e.target.files?.[0];if(!file)return;try{if(file.size>1000000)throw Error('Maximum file size is 1 MB');setRows(parseLeadCsv(await file.text()));}catch(e){setError(e instanceof Error?e.message:'Invalid CSV');}}}/>{error&&<p role="alert" className="my-4 text-red-700">{error}</p>}{result&&<p role="status" className="my-4 text-green-700">{result}</p>}{!!rows.length&&<><h2 className="my-4 font-semibold">Preview: {rows.length} leads</h2><div className="max-h-96 overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{['Name','Company','Phone','Email','Source'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr className="border-t" key={i}>{['contactName','businessName','phone','email','source'].map(k=><td className="p-2" key={k}>{r[k]||'—'}</td>)}</tr>)}</tbody></table></div><button className="mt-4 rounded bg-blue-600 px-4 py-2 text-white" disabled={busy} onClick={submit}>{busy?'Importing…':`Import ${rows.length} Leads`}</button></>}</main>;
}
